### ISSUE TITLE
Map active note parameters into useful ranges

### ISSUE THREAD

**Issue by odub** [WeAreROLI/mpejs#22]
Currently `pitchBend`, `pressure` and `timbre` return 7-bit unsigned integers.

It would be convenient to give an option that mapped `timbre` and `pressure` between 0 and 1, and mapped `pitchBend` between -1 and 1. Probably this should be the default.

So:
I suggest adding a `rawValues` option to `mpeInstrument`. If `false` (default) `activeNotes` and `subscribe` would return the mapped values described above. If `true`, return the current 7-bit and 14-bit unsigned integers instead.

EDIT: new plan https://github.com/WeAreROLI/mpejs/issues/22#issuecomment-262600725

**Comment by odub** [comment]
Before:
```js
import mpeInstrument from 'mpe';

const instrument = mpeInstrument();

instrument.activeNotes();
// => []

instrument.processMidiMessage([145, 60, 127]);
instrument.activeNotes();
// => [ { noteNumber: 60,
//        channel: 2,
//        noteOnVelocity: 127,
//        pitchBend: 8192,
//        timbre: 8192,
//        pressure: 0 } ]
```

After:
```
import mpeInstrument from 'mpe';

const instrument = mpeInstrument();

instrument.activeNotes();
// => []

instrument.processMidiMessage([145, 60, 127]);
instrument.activeNotes();
// => [ { noteNumber: 60,
//        channel: 2,
//        noteOnVelocity: 127,
//        pitchBend: 0,
//        timbre: 0,
//        pressure: 0 } ]
```

**Comment by odub** [comment]
New plan here after a useful discussion with @jordanstephens.

Result:
* the current output stays the default – no need for a `rawValues` option
* add an option called `simple` or something similar
* when `simple` is true:
  * remap `timbre`, `pressure` and `noteNumber` between 0 and 1
  * remap `pitchBend` between -1 and 1
  * add a `pitch` key with `noteNumber` converted like `60 -> 'C4'` etc.

**Comment by odub** [comment]
Thinking about this more, the `noteNumber` to pitch conversion should maybe be a different flag from this one. That would also mean the range remapping could be called something like `normalizeValues` or `normalize` and the module could offer a choice of pitch display conventions.

**Comment by tomduncalf** [comment]
Agree with version 3 of the plan :) I think keeping defaults as the "raw" MIDI versions for notes certainly makes sense, not sure which is preferable for continuous values but as long as the `normalize` option is well signposted, it shouldn't matter too much
