### ISSUE TITLE
What is the License?

### ISSUE THREAD

**Issue by khoin** [WeAreROLI/mpejs#44]
There's no LICENSE file, but in package.json I see this: https://github.com/WeAreROLI/mpejs/blob/master/package.json#L15

Says "UNLICENSED". Do you mean this is public domain as said here? http://unlicense.org/

**Comment by odub** [comment]
`'UNLICENSED' !== 'UNLICENSE'`, I was working to the description here:
https://docs.npmjs.com/files/package.json

On the other hand, it's likely there'll be a much more permissive license very shortly. The current state was chosen as a stopgap from the initial development period where I was more worried about the tool not existing than its legal status.

Keep an eye out for updates in the next few days and thanks for flagging this.

**Comment by khoin** [comment]
Thanks the reply! I was planning on implementing from the spec, but I realize you already made this library, so I figured I should get lazy :P I'll keep this issue opened for now until you decide the license.
