### ISSUE TITLE
Examples of loading midi from file

### ISSUE THREAD

**Issue by shark8me** [WeAreROLI/mpejs#57]
Hi,
I love the idea of this API!

I'm interested in functionality of reading the midi events off a stream (while reading a midi file) to post-process the events. Could you please share or point out an example of how this could be achieved?

Thanks!

**Comment by odub** [comment]
Hi Kiran,

> I love the idea of this API!

Shucks, thanks!

> I'm interested in functionality of reading the midi events off a stream (while reading a midi file) to post-process the events. Could you please share or point out an example of how this could be achieved?

Here's something off the top of my head, but I'm worried I may not fully understand your use case, so please give additional details about what you're trying to do (ideally about the application too) and I'll do my best to help more.

I'm assuming your stream emits midi message events that are objects with the shape:
```js
{
  message: Uint8Array[3], // raw midi message
  deltaTime: Number, // time since the previous event in ticks
   // … any other event properties …
}
```

Then your code could look like:
```js
import mpeInstrument from 'mpe';

// const stream =  { … here's where to instantiate your midi file reader stream … };
const time = 0;

stream.onmidimessage = (event) => {
  const { message, deltaTime } = event;
  time += deltaTime;
  mpeInstrument.processMidiMessage(message);
  const postProcessedState = {
    time, // can be translated into musical time (beats) or clock time (ms or s)
    activeNotes: mpeInstrument.activeNotes(),
  };
  // … do stuff with your `postProcessedState` state here …
}
```

NB. `postProcessedState` would be an extremely verbose data representation. For storage purposes or sending over the network, you're definitely better off with either the original .mid format or a minimal JSON representation like:

```
[
  {
    "message": Array[3],
    "deltaTime": Number,
  },
  …
]
```

Hope this helps!

Oscar

**Comment by shark8me** [comment]
Thanks for the quick response! 

Here's my application:
I've recorded and saved (as MPE compatible MIDI) a session recorded with the Roli Rise. I'd like to transform the midi to 
* remove certain keys entirely from the performance
* transpose certain keys
and then re-write the MIDI file out. I'd like to build a small DSL/library that achieves the same. 

Would this be possible with mpe.js? 

Thanks!

**Comment by odub** [comment]
Hrm, that's a really interesting one.

I can think of ways to use this library to help with those tasks, but it's definitely bending mpe.js away from intended usage.

For this one:

> remove certain keys entirely from the performance

A simplistic way to implement this would be to store the channel of 'Note On' messages when reading in the stream, and then, when writing, filter out all further events on that channel until a matching 'Note Off' comes through.

For this:

> transpose certain keys and then re-write the MIDI file out. I'd like to build a small DSL/library that achieves the same.

Here, the simple approach would be to modify the first data byte of matched pairs of 'Note On' and 'Note Off' messages in the stream (ensuring they're on the same channel) based on whatever transposition you want to apply. If you want transpositions that aren't an integer number of semitones you'll need something a bit more complex.
