### ISSUE TITLE
Detect Where on the Key A User Touches

### ISSUE THREAD

**Issue by jonobr1** [WeAreROLI/mpejs#62]
I've been using the Seabord Block to create visuals for musicians in live music settings. It's a great tool to quickly and expressively connect visuals with audio. Thanks for the work on this handy library.

I was wondering.., is there a way know where on the key a user touches? the `timbre` property from the subscribe event seems to have some indication of vertical movement of a touch, but it would be amazing to know precisely where on the key a user touches. It would give me more control on whether a black key or white key was intended to be pressed.

Thanks for the great library and if you're in the Paris area I'll be using this library along with my Seabord to do visuals at this event: https://gaite-lyrique.net/en/event/nuit-blanche-2019

( My set starts at 1.30AM )

**Comment by felixfaire** [comment]
Hey Jono. i'm not sure about the specifics of mpe.js (oscar might be able to help with that) but having done visuals with the seaboard (rise) before I can say this is definitely possible with MPE. Though might need to make your own mapping function from (note number, pitchbend, timbre) -> (x, y).

Its been a while and the seaboard block may have different ranges (you should be able to check in ROLI Dashboard), but i think it was something like this.

Y Axis:
Timbre is effectively y axis position (double check dashboard as i think there is also a relative mode as well as absolute).

X Axis:
noteNumber + pitchbendRangeSemitones * pitchBend / 8192.0
set your pitchbend range [here](https://rolisupport.freshdesk.com/support/solutions/articles/36000028378-setting-the-ideal-pitch-bend-range) 

Hope this helps

The event looks great, will be a shame to miss it.

**Comment by jonobr1** [comment]
That is super helpful. Thanks! Maybe I should update my firmware on my seabord as well...

**Comment by jonobr1** [comment]
The Roku Dashboard did the trick. Thanks so much for creating a device and interface to JavaScript. I was able to successfully run visuals on a 360° screen because of it. If you're interested, here's a short video clip from the event: https://photos.app.goo.gl/o8bhtT4nt7zx6BBY8
